# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               MnT
tagline:             A Blog on Math and Tech
url:                 http://ecrirai.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nicolas
  # url:               https://x.com/ngrislain
  # email:             nicolasgrislain@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/ecrirai/ecrirai.github.io

# Setup MathJAX
kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    disable: true